---
title: "Project_implementation_log"
author: "Rafal Bazan"
date: "2024-05-25"
output: html_document
---

```{r setup, include=FALSE}
project_path = "D:/moje/projekty/chess-in-the-digital-age"

knitr::opts_chunk$set(root= paste(project_path,"/log", sep = ""))
setwd(paste(project_path,"/log", sep = ""))
```

# Automatyzacja pracy

#### Marzec: 

- Wybranie dziedziny badań projektu, zapoznanie z bazą danych lichess i pierwszy import danych. Znaleziono sposób importu danych ze stackoverflow

- Problem: zaproponowany kod nie uwzględnia braku danych lub ich nadmiaru

#### 14 maj: 

- Wybór tematów do zbadania

#### 15 maj: 

- Zapoznanie ze statystykami z zewnętrznych stron i ocenienie czy zrealizowanie projektu ma sens

#### 16 maj: 

- Przygotowanie planu działań

#### 17 maj: 

- Rozpoczęcie pobierania danych ze strony lichess 

- Problem: zbyt duże zbiory danych

  - Rozwiązanie: pobranie jak największej ilości danych i zamienienie ich na kopie w R z taką ilością w odpowiednim 
stosunku, by się pomieściły na dysku.

- Problem: za mało ramu do przeanalizowania całych zbiorów danych

  - Rozwiązanie: ograniczenie danych za pomocą R by analizowały tylko początkowe fragmenty zbiorów.

#### 20 maj:

- Planowanie wykorzystania funkcji rm() dla możliwości analizowania większych zbiorów

#### 21 maj:

- Ponowna instalacja z lichess z podaną strukturą katalogową dzięki skryptowi w bashu

```{shell eval=FALSE}
for year in {2013..2024}; do
    mkdir -p $year
    for month in {1..12}; do
        case $month in
            1) month_name="01. January" ;;
            2) month_name="02. February" ;;
            3) month_name="03. March" ;;
            4) month_name="04. April" ;;
            5) month_name="05. May" ;;
            6) month_name="06. June" ;;
            7) month_name="07. July" ;;
            8) month_name="08. August" ;;
            9) month_name="09. September" ;;
            10) month_name="10. October" ;;
            11) month_name="11. November" ;;
            12) month_name="12. December" ;;
        esac
        mkdir -p $year/"$month_name"
    done
done
```

- Problem: Do każdego folderu trzeba pobrać plik ze strony (a tego sporo, już sie wcześniej pogubiłem i musiałem wszystko od nowa pobierać) (da się to wykonać scrapowaniem)

  - Rozwiązanie wykonanie scrapowania z jednoczesnym pobieraniem plików do odpowiednich folderów w R

- Działa wyodrębnianie linku do pobierania scrapowaniem

- Dziala pobieranie na podstawie gotowego linku 

- Trzeba uzyskać gotowy link ze scrapowania i to zautomatyzować z pobieraniem

#### 22 maj: 

- Scrapowanie linków i pobieranie ich ze strony działa, teraz to zautomatyzować

- Tworzenie dataframe z linkami

- Problem: do komendy pobierania ścieżka też musi być dataframe o tej samej długości

  - Rozwiazanie: stworzenie dataframe gdzie każdy wiersz jest tą samą ścieżką 

- Problem: zdefiniowana ścieżka do pobierania musi zawierać również nazwę pobieranego pliku

- Problem: pobrane pliki nie są możliwe do instalacji przez error (torrent jest błędnie kodowany)

  - Rozwiązanie: przy komendzie pobierania należy zmienić metodę pobierania na "wb" ( binarne pobieranie)

#### 23 maj:

- Tworzenie data.frame z nazwami sciezek dla do późniejszejszego pobierania tam danych

- Problem: stworzenie odpowiedniej struktury rok-miesiac

  - Rozwiązanie: wykorzystać regexp do pobrania daty z linków ze-scrapowanych wcześniej ze strony

- Problem: regex

  - sprawdzanie metody \\p{N}

  - sprawdzanie metody (?<=rated_)\\w+ (Zwraca tylko rok bez miesiąca)

  - sprawdzanie stri_sub (nie działa na ramkach tylko wektorach)

  - sprawdzanie regmatches

- Działa metoda stri_match_all

- Do stworzenia ścieżki trzeba dane jako lista a nie data.frame

- Problem: mam numer miesiąca jako str...funkcja month.abb[ ] nie przyjmuje str...

  - Rozwiazanie: zmiana danych na liczbową

#### 24 maj:

- Tworzenie struktury folderów na podstawie dostępnej zmiennej ze ścieżkami

- Problem: create.dir() nie może tworzyć wiele folderów na raz
  
  - Rozwiązanie: Tworzenie pętelki for

- Problem download.file() ma problem w działaniu dla wielu elementów

  - Rozwiązanie: zrobienie pętelki która pojedynczo pobiera po kolei pliki

- Problem: download.file() jako argumenty bierze listy, a linki do pobrania muszą być w formie data.frame

  - Rozwiązanie: tylko kolumnę pobierać z dataframe - linki[j, ]

- Problem: z serwera nie można w zbyt szybkim tempie pobierać dużej ilości plików

  - Rozwiązanie: podzielenie funkcji na dwa zbiory po połowie i po wykonaniu jednej wykonuje się sleep, następnie drugi zbiór się wykonuje

- Problem: pobieranie wykonuje się asynchronicznie, przez co sleep jest mało efektywny

  - Rozwiązanie: funkcja download.file() przyjmuje dodatkowe argumenty, więc dodałem do niej sys.sleep(0.2)

- Rozpoczęcie instalacji danych z 2024 roku i 2023 roku

### Tworzenie struktury działa, oraz pobieranie instalek do odpowiednich folderów

# Tworzenie zbiorów danych

#### 25 maj:

- Tworzenie przycisku w java-script do ukrycia zawartości kodu odnośnie tworzenia struktury plików

- Rozpoczęcie instalacji zbiorów danych z 2022 roku

- Tworzenie funkcji, która generuje gotowy data.frame dla danego miesiąca

- Problem: ilość ramu nie pozwala na ograniczenie zbioru dla danego miesiąca korzystając z długości wierszy...(potrafi liczyć prawie 2 miliardy linijek jeden miesiąc)

- Rozwiązanie: ograniczenie zbiorów danego miesiąca na podstawie ilości zagranych partii w tym miesiącu jako 1% (ilość meczy należy pomnożyć przez 18 ponieważ około tyle linijek zawiera jeden mecz)

- Problem: zbiór ilości partii dla danego miesiąca, trzeba przerobic na typ numeryczny, ale nie jest to dostępne bo liczby są dzielone separatorem ", "

- Rozwiązanie: usunięcie ", " z zescrapowanych danych

- Problem: stri_trans_char nie chce zmienić ", " na " "

- Rozwiązanie: stri_replace_all może zmienić ", " na " "

- Problem: ilosc wierszy do ucięcia nie może być w typie double tylko integer...zmiana z as.numeric na as.integer jest nie mozliwa

- Rozwiązanie: zaokrąglenie wartości 

- tworzenie funkcji gotowej przerobić zbiór danego miesiąca wedle kryteriów

#### 26 maj:

- Zmiana funkcji do generowania struktury i pobierania plików tak by użytkownik mógł stwierdzić do jakiego roku chce pobierać dane (bez tego gdyby ktoś uruchomił kod w czerwcu, cały kod mógłby nie działać)

- stworzenie funkcji do ograniczania oryginalnego zbioru według podanej daty

- stworzenie funkcji do usuwania oryginalnych zbiorów według podanej daty

### Problem: nic nie działa

- Rozwiązanie: z jakiegoś powodu komenda do wyznaczania godziny z linku zaczęła wypisywać dane w jednym wierszu... trzeba było zmienić w jednym miejscu argument jako data.frame

- Uwzględnienie wyboru lat do zescrapowania dla liczb partii względem miesiąca

- Rozpoczęcie instalacji zbiorów danych z 2021 roku

### działają funkcje do automatycznej redukcji wielkości danych... teraz tylko pobierać dane i stworzyć funkcje do tworzenia zbioru danych w postaci tabelarycznej

# Przygotowywanie zbiorów do analizy

#### 28 maj:

- Pobieranie danych z 2021 i 2020 roku

- pierwsze testy tworzenia gotowych zbiorów

- wyodrębnianie tytułów które się zawsze powtarzają dzięki fct_count(), analizowane zbiory teraz można ograniczyć by miały w sobie tylko podane tytuły...dzięki temu zmieniając zbiory na macierze, się nie rozjeżdżają 

- dane z 2024 są już zdekompresowane i ograniczone

#### 29 maj:

- Pobieranie danych z 2019 roku i niewielkie przygotowania danych

#### 30 maj: 

- Problem: kod jest mało kolorowy

- Rozwiązanie: szukanie informacji o lepszym kolorowaniu kodu...lsp...rstudio nie oferuje, więc przepisałem kod do emacsa który oferuje kolorowanie kodu, 

- Problem: nieprawidłowo sie wyświetla fragment kodu przy użyciu pander

- Rozwiązanie: pozostanie przy rstudio

- Re-factor kodu i podstawowe zmiany wizualizalne

- Problem: pander ma problem z wyświetleniem linków jako zwykły tekst

- Rozwiazanie: paczki malaysia nie rozwiązuje problemu, kableExtra nie może się zainstalować, cały czas mam komunikat: nie można przekształcić xml_nodeset w klasę data.frame...pominąłem więc wyświetlanie tego elementu ( w dalszej części kodu itak jest już wyświetlany link poprawnie)

- zdekompresowano i ograniczono dane z 2023 roku

- Skończono Pobieranie danych

- pierwsze testy z porównywaniem list w innej kolejności

# Analiza danych

#### 31 maj:

#### Problem: kod nie chce sie wykonywać w R

- Rozwiązanie: przez to ze wyswietlam mój css w html, sposobem na ukrywanie fragmentów kodu dzięki jv, musze stworzyc odrebny fragment kodu css z ustawieniem (echo=FALSE)(który będzie poza niewyswietlanym div-em) oraz odrębny kod z ustawieniem (eval=FALSE) (który będzie w niewyświetlanym div-ie)

- Tworzenie wykresu ze scrapowania

- problem: nie mogę wyświetlać każdego miesiąca jako nazwy argumentów

- wyodrębnianie ze scrapowania tylko unikalnych lat

- Problem: nic to nie daje, nadal nie da się zmienić wartości dla x, wykres przyjmując argumenty x jako tekst sprawia że nie można zmienić jego zawartości, wartości y nie akceptują dużych liczb

- Rozwiązanie: zawartość zbioru x zmieniłem na zakres 1: 136 i potem w wyszukane indexy gdzie się znajduje początek danego roku pojawią się label z unikalna nazwą roku, wartości y sformatowano dla skali M "milion"

- dodano zdjęcia i strzałkę do wykresu

- zdekompresowano dane do 2021 roku

#### 1 czerwiec

- zdekompresowano wszystkie dane

- rozpoczęto przetwarzanie zbiorów

- By szybko wyszukać ilość zagranych debiutów gambit królowej najlepiej to trzeba ze zbioru danych wyodrębnić tylko tą kolumnę

- Problem: zbiór danych ma braki lub ich jest za dużo, przez co cały zbiór się rozjeżdża

- rozwiazanie: wyszukać dane które występują rzadziej niż reszta i je potem usunąć po indeksach jesli nie są  potrzebne dla analizy, następnie zmienić równe dane na macierz 

- problem: dane z 2024 roku mają 17 kolumn w nie zmiennych ilosciach, a dane z 2013 mają 13, więc albo zrobić funkcje która będzie brać tylko 13 konkretnych kolumn do analizy (inne lata mogą mieć inne kolumny nie zmienne)
Lub funkcje która będzie brać tylko indeksy ze zmienną opening i wśród nich gambit królowej

- Rozwiązanie: druga opcja

 - Problem: ze statystyk wynika że popularność grania gambitem królowej maleje

- Rozwiazanie: prawdopodobnie wynik powoduje wzrost nowicjuszy grających w szachy

- liczby w stosunku do maksymalnej liczby partii w miesiącu są mało czytelne, zmiana na zwykły wynik

- zwykły wynik jest tym bardziej nie czytelny

#### 2 czerwiec

- stworzono wykresy dzielące nowicjuszy i zaawansowanych graczy

- wyodrębnianie 5 ruchów szachowych w wybranej partii w poszukiwaniu sekwencji 

#### 3 czerwiec

- zautomatyzowano wyodrębnianie wszystkich ruchów szachowych gracza w partii

#### 4 czerwiec

- wyodrębnianie 2 pierwszych posunięć w partii

- Problem: metoda unlist i wyodrębnianie dwóch wektorów co 6 wektorów nie uwzględnia braków danych i się wszystko rozjeżdża 

#### 6 czerwiec

- Rozwiązanie: stworzenie funkcji która porównuję wzorzec pięciu ruchów z każdą partią, używając zapętlania for()

- Problem: kod do wyszukiwania partii względem posunięć wykonuje się zbyt długo (pół miesiąca w 7 godzin)

#### 7 czerwiec

- Rozwiązanie: zamiast porównywać każdą partie ze wzorcem, porównuję tylko pierwsze posunięcia partii ze wzorcem, zyskując index pierwszych posunięć które się zgadzają ze wzorcem. W następnych krokach wyszukiwanie odbywa się tylko na wzorcach z wcześniejszego kroku, i tak sie powtarza tyle razy ile ma ruchów wzorzec (to Rozwiązanie uzywa tylko 5 pętelek dla miesiąca zamiast 90 000 i przy każdym kroku ma coraz mniej do wyszukiwania)

- Efekt: Zamiast analizować pół miesiąca w 7 godzin, wszystkie 140 miesięcy wykonuje się w 8 minut

#### 8 czerwiec

- kończenie prezentacji

#### 9 czerwiec

- zrobienie funkcji do generowania posunięć szachowych względem wzorca

- zrobienie plakatu
